package com;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/authenticator.proto
// Protobuf Java Version: 4.27.0

public final class Authenticator {
  private Authenticator() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      Authenticator.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MigrationPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MigrationPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    java.util.List<Authenticator.MigrationPayload.OtpParameters> 
        getOtpParametersList();
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    Authenticator.MigrationPayload.OtpParameters getOtpParameters(int index);
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    int getOtpParametersCount();
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    java.util.List<? extends Authenticator.MigrationPayload.OtpParametersOrBuilder> 
        getOtpParametersOrBuilderList();
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    Authenticator.MigrationPayload.OtpParametersOrBuilder getOtpParametersOrBuilder(
        int index);

    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>int32 batch_size = 3;</code>
     * @return The batchSize.
     */
    int getBatchSize();

    /**
     * <code>int32 batch_index = 4;</code>
     * @return The batchIndex.
     */
    int getBatchIndex();

    /**
     * <code>int32 batch_id = 5;</code>
     * @return The batchId.
     */
    int getBatchId();
  }
  /**
   * Protobuf type {@code MigrationPayload}
   */
  public static final class MigrationPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MigrationPayload)
      MigrationPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 0,
        /* suffix= */ "",
        MigrationPayload.class.getName());
    }
    // Use MigrationPayload.newBuilder() to construct.
    private MigrationPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MigrationPayload() {
      otpParameters_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Authenticator.internal_static_MigrationPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Authenticator.internal_static_MigrationPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Authenticator.MigrationPayload.class, Authenticator.MigrationPayload.Builder.class);
    }

    /**
     * Protobuf enum {@code MigrationPayload.Algorithm}
     */
    public enum Algorithm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALGORITHM_UNSPECIFIED = 0;</code>
       */
      ALGORITHM_UNSPECIFIED(0),
      /**
       * <code>ALGORITHM_SHA1 = 1;</code>
       */
      ALGORITHM_SHA1(1),
      /**
       * <code>ALGORITHM_SHA256 = 2;</code>
       */
      ALGORITHM_SHA256(2),
      /**
       * <code>ALGORITHM_SHA512 = 3;</code>
       */
      ALGORITHM_SHA512(3),
      /**
       * <code>ALGORITHM_MD5 = 4;</code>
       */
      ALGORITHM_MD5(4),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 27,
          /* patch= */ 0,
          /* suffix= */ "",
          Algorithm.class.getName());
      }
      /**
       * <code>ALGORITHM_UNSPECIFIED = 0;</code>
       */
      public static final int ALGORITHM_UNSPECIFIED_VALUE = 0;
      /**
       * <code>ALGORITHM_SHA1 = 1;</code>
       */
      public static final int ALGORITHM_SHA1_VALUE = 1;
      /**
       * <code>ALGORITHM_SHA256 = 2;</code>
       */
      public static final int ALGORITHM_SHA256_VALUE = 2;
      /**
       * <code>ALGORITHM_SHA512 = 3;</code>
       */
      public static final int ALGORITHM_SHA512_VALUE = 3;
      /**
       * <code>ALGORITHM_MD5 = 4;</code>
       */
      public static final int ALGORITHM_MD5_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Algorithm valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Algorithm forNumber(int value) {
        switch (value) {
          case 0: return ALGORITHM_UNSPECIFIED;
          case 1: return ALGORITHM_SHA1;
          case 2: return ALGORITHM_SHA256;
          case 3: return ALGORITHM_SHA512;
          case 4: return ALGORITHM_MD5;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Algorithm> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
              public Algorithm findValueByNumber(int number) {
                return Algorithm.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Authenticator.MigrationPayload.getDescriptor().getEnumTypes().get(0);
      }

      private static final Algorithm[] VALUES = values();

      public static Algorithm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Algorithm(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MigrationPayload.Algorithm)
    }

    /**
     * Protobuf enum {@code MigrationPayload.DigitCount}
     */
    public enum DigitCount
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DIGIT_COUNT_UNSPECIFIED = 0;</code>
       */
      DIGIT_COUNT_UNSPECIFIED(0),
      /**
       * <code>DIGIT_COUNT_SIX = 1;</code>
       */
      DIGIT_COUNT_SIX(1),
      /**
       * <code>DIGIT_COUNT_EIGHT = 2;</code>
       */
      DIGIT_COUNT_EIGHT(2),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 27,
          /* patch= */ 0,
          /* suffix= */ "",
          DigitCount.class.getName());
      }
      /**
       * <code>DIGIT_COUNT_UNSPECIFIED = 0;</code>
       */
      public static final int DIGIT_COUNT_UNSPECIFIED_VALUE = 0;
      /**
       * <code>DIGIT_COUNT_SIX = 1;</code>
       */
      public static final int DIGIT_COUNT_SIX_VALUE = 1;
      /**
       * <code>DIGIT_COUNT_EIGHT = 2;</code>
       */
      public static final int DIGIT_COUNT_EIGHT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DigitCount valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DigitCount forNumber(int value) {
        switch (value) {
          case 0: return DIGIT_COUNT_UNSPECIFIED;
          case 1: return DIGIT_COUNT_SIX;
          case 2: return DIGIT_COUNT_EIGHT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DigitCount>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DigitCount> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DigitCount>() {
              public DigitCount findValueByNumber(int number) {
                return DigitCount.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Authenticator.MigrationPayload.getDescriptor().getEnumTypes().get(1);
      }

      private static final DigitCount[] VALUES = values();

      public static DigitCount valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DigitCount(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MigrationPayload.DigitCount)
    }

    /**
     * Protobuf enum {@code MigrationPayload.OtpType}
     */
    public enum OtpType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OTP_TYPE_UNSPECIFIED = 0;</code>
       */
      OTP_TYPE_UNSPECIFIED(0),
      /**
       * <code>OTP_TYPE_HOTP = 1;</code>
       */
      OTP_TYPE_HOTP(1),
      /**
       * <code>OTP_TYPE_TOTP = 2;</code>
       */
      OTP_TYPE_TOTP(2),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 27,
          /* patch= */ 0,
          /* suffix= */ "",
          OtpType.class.getName());
      }
      /**
       * <code>OTP_TYPE_UNSPECIFIED = 0;</code>
       */
      public static final int OTP_TYPE_UNSPECIFIED_VALUE = 0;
      /**
       * <code>OTP_TYPE_HOTP = 1;</code>
       */
      public static final int OTP_TYPE_HOTP_VALUE = 1;
      /**
       * <code>OTP_TYPE_TOTP = 2;</code>
       */
      public static final int OTP_TYPE_TOTP_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OtpType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static OtpType forNumber(int value) {
        switch (value) {
          case 0: return OTP_TYPE_UNSPECIFIED;
          case 1: return OTP_TYPE_HOTP;
          case 2: return OTP_TYPE_TOTP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OtpType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OtpType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OtpType>() {
              public OtpType findValueByNumber(int number) {
                return OtpType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Authenticator.MigrationPayload.getDescriptor().getEnumTypes().get(2);
      }

      private static final OtpType[] VALUES = values();

      public static OtpType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private OtpType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MigrationPayload.OtpType)
    }

    public interface OtpParametersOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MigrationPayload.OtpParameters)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>bytes secret = 1;</code>
       * @return The secret.
       */
      com.google.protobuf.ByteString getSecret();

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string issuer = 3;</code>
       * @return The issuer.
       */
      java.lang.String getIssuer();
      /**
       * <code>string issuer = 3;</code>
       * @return The bytes for issuer.
       */
      com.google.protobuf.ByteString
          getIssuerBytes();

      /**
       * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
       * @return The enum numeric value on the wire for algorithm.
       */
      int getAlgorithmValue();
      /**
       * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
       * @return The algorithm.
       */
      Authenticator.MigrationPayload.Algorithm getAlgorithm();

      /**
       * <code>.MigrationPayload.DigitCount digits = 5;</code>
       * @return The enum numeric value on the wire for digits.
       */
      int getDigitsValue();
      /**
       * <code>.MigrationPayload.DigitCount digits = 5;</code>
       * @return The digits.
       */
      Authenticator.MigrationPayload.DigitCount getDigits();

      /**
       * <code>.MigrationPayload.OtpType type = 6;</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.MigrationPayload.OtpType type = 6;</code>
       * @return The type.
       */
      Authenticator.MigrationPayload.OtpType getType();

      /**
       * <code>int64 counter = 7;</code>
       * @return The counter.
       */
      long getCounter();
    }
    /**
     * Protobuf type {@code MigrationPayload.OtpParameters}
     */
    public static final class OtpParameters extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:MigrationPayload.OtpParameters)
        OtpParametersOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 27,
          /* patch= */ 0,
          /* suffix= */ "",
          OtpParameters.class.getName());
      }
      // Use OtpParameters.newBuilder() to construct.
      private OtpParameters(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private OtpParameters() {
        secret_ = com.google.protobuf.ByteString.EMPTY;
        name_ = "";
        issuer_ = "";
        algorithm_ = 0;
        digits_ = 0;
        type_ = 0;
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Authenticator.internal_static_MigrationPayload_OtpParameters_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Authenticator.internal_static_MigrationPayload_OtpParameters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Authenticator.MigrationPayload.OtpParameters.class, Authenticator.MigrationPayload.OtpParameters.Builder.class);
      }

      public static final int SECRET_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString secret_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes secret = 1;</code>
       * @return The secret.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSecret() {
        return secret_;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ISSUER_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object issuer_ = "";
      /**
       * <code>string issuer = 3;</code>
       * @return The issuer.
       */
      @java.lang.Override
      public java.lang.String getIssuer() {
        java.lang.Object ref = issuer_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          issuer_ = s;
          return s;
        }
      }
      /**
       * <code>string issuer = 3;</code>
       * @return The bytes for issuer.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIssuerBytes() {
        java.lang.Object ref = issuer_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          issuer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ALGORITHM_FIELD_NUMBER = 4;
      private int algorithm_ = 0;
      /**
       * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
       * @return The enum numeric value on the wire for algorithm.
       */
      @java.lang.Override public int getAlgorithmValue() {
        return algorithm_;
      }
      /**
       * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
       * @return The algorithm.
       */
      @java.lang.Override public Authenticator.MigrationPayload.Algorithm getAlgorithm() {
        Authenticator.MigrationPayload.Algorithm result = Authenticator.MigrationPayload.Algorithm.forNumber(algorithm_);
        return result == null ? Authenticator.MigrationPayload.Algorithm.UNRECOGNIZED : result;
      }

      public static final int DIGITS_FIELD_NUMBER = 5;
      private int digits_ = 0;
      /**
       * <code>.MigrationPayload.DigitCount digits = 5;</code>
       * @return The enum numeric value on the wire for digits.
       */
      @java.lang.Override public int getDigitsValue() {
        return digits_;
      }
      /**
       * <code>.MigrationPayload.DigitCount digits = 5;</code>
       * @return The digits.
       */
      @java.lang.Override public Authenticator.MigrationPayload.DigitCount getDigits() {
        Authenticator.MigrationPayload.DigitCount result = Authenticator.MigrationPayload.DigitCount.forNumber(digits_);
        return result == null ? Authenticator.MigrationPayload.DigitCount.UNRECOGNIZED : result;
      }

      public static final int TYPE_FIELD_NUMBER = 6;
      private int type_ = 0;
      /**
       * <code>.MigrationPayload.OtpType type = 6;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MigrationPayload.OtpType type = 6;</code>
       * @return The type.
       */
      @java.lang.Override public Authenticator.MigrationPayload.OtpType getType() {
        Authenticator.MigrationPayload.OtpType result = Authenticator.MigrationPayload.OtpType.forNumber(type_);
        return result == null ? Authenticator.MigrationPayload.OtpType.UNRECOGNIZED : result;
      }

      public static final int COUNTER_FIELD_NUMBER = 7;
      private long counter_ = 0L;
      /**
       * <code>int64 counter = 7;</code>
       * @return The counter.
       */
      @java.lang.Override
      public long getCounter() {
        return counter_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!secret_.isEmpty()) {
          output.writeBytes(1, secret_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(issuer_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 3, issuer_);
        }
        if (algorithm_ != Authenticator.MigrationPayload.Algorithm.ALGORITHM_UNSPECIFIED.getNumber()) {
          output.writeEnum(4, algorithm_);
        }
        if (digits_ != Authenticator.MigrationPayload.DigitCount.DIGIT_COUNT_UNSPECIFIED.getNumber()) {
          output.writeEnum(5, digits_);
        }
        if (type_ != Authenticator.MigrationPayload.OtpType.OTP_TYPE_UNSPECIFIED.getNumber()) {
          output.writeEnum(6, type_);
        }
        if (counter_ != 0L) {
          output.writeInt64(7, counter_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!secret_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, secret_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(issuer_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(3, issuer_);
        }
        if (algorithm_ != Authenticator.MigrationPayload.Algorithm.ALGORITHM_UNSPECIFIED.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(4, algorithm_);
        }
        if (digits_ != Authenticator.MigrationPayload.DigitCount.DIGIT_COUNT_UNSPECIFIED.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(5, digits_);
        }
        if (type_ != Authenticator.MigrationPayload.OtpType.OTP_TYPE_UNSPECIFIED.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(6, type_);
        }
        if (counter_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(7, counter_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Authenticator.MigrationPayload.OtpParameters)) {
          return super.equals(obj);
        }
        Authenticator.MigrationPayload.OtpParameters other = (Authenticator.MigrationPayload.OtpParameters) obj;

        if (!getSecret()
            .equals(other.getSecret())) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (!getIssuer()
            .equals(other.getIssuer())) return false;
        if (algorithm_ != other.algorithm_) return false;
        if (digits_ != other.digits_) return false;
        if (type_ != other.type_) return false;
        if (getCounter()
            != other.getCounter()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SECRET_FIELD_NUMBER;
        hash = (53 * hash) + getSecret().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + ISSUER_FIELD_NUMBER;
        hash = (53 * hash) + getIssuer().hashCode();
        hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
        hash = (53 * hash) + algorithm_;
        hash = (37 * hash) + DIGITS_FIELD_NUMBER;
        hash = (53 * hash) + digits_;
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + COUNTER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCounter());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static Authenticator.MigrationPayload.OtpParameters parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static Authenticator.MigrationPayload.OtpParameters parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static Authenticator.MigrationPayload.OtpParameters parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Authenticator.MigrationPayload.OtpParameters prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MigrationPayload.OtpParameters}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MigrationPayload.OtpParameters)
          Authenticator.MigrationPayload.OtpParametersOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Authenticator.internal_static_MigrationPayload_OtpParameters_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Authenticator.internal_static_MigrationPayload_OtpParameters_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Authenticator.MigrationPayload.OtpParameters.class, Authenticator.MigrationPayload.OtpParameters.Builder.class);
        }

        // Construct using Authenticator.MigrationPayload.OtpParameters.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          secret_ = com.google.protobuf.ByteString.EMPTY;
          name_ = "";
          issuer_ = "";
          algorithm_ = 0;
          digits_ = 0;
          type_ = 0;
          counter_ = 0L;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Authenticator.internal_static_MigrationPayload_OtpParameters_descriptor;
        }

        @java.lang.Override
        public Authenticator.MigrationPayload.OtpParameters getDefaultInstanceForType() {
          return Authenticator.MigrationPayload.OtpParameters.getDefaultInstance();
        }

        @java.lang.Override
        public Authenticator.MigrationPayload.OtpParameters build() {
          Authenticator.MigrationPayload.OtpParameters result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public Authenticator.MigrationPayload.OtpParameters buildPartial() {
          Authenticator.MigrationPayload.OtpParameters result = new Authenticator.MigrationPayload.OtpParameters(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(Authenticator.MigrationPayload.OtpParameters result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.secret_ = secret_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.name_ = name_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.issuer_ = issuer_;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.algorithm_ = algorithm_;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.digits_ = digits_;
          }
          if (((from_bitField0_ & 0x00000020) != 0)) {
            result.type_ = type_;
          }
          if (((from_bitField0_ & 0x00000040) != 0)) {
            result.counter_ = counter_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Authenticator.MigrationPayload.OtpParameters) {
            return mergeFrom((Authenticator.MigrationPayload.OtpParameters)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Authenticator.MigrationPayload.OtpParameters other) {
          if (other == Authenticator.MigrationPayload.OtpParameters.getDefaultInstance()) return this;
          if (other.getSecret() != com.google.protobuf.ByteString.EMPTY) {
            setSecret(other.getSecret());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (!other.getIssuer().isEmpty()) {
            issuer_ = other.issuer_;
            bitField0_ |= 0x00000004;
            onChanged();
          }
          if (other.algorithm_ != 0) {
            setAlgorithmValue(other.getAlgorithmValue());
          }
          if (other.digits_ != 0) {
            setDigitsValue(other.getDigitsValue());
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (other.getCounter() != 0L) {
            setCounter(other.getCounter());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  secret_ = input.readBytes();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  name_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  issuer_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                case 32: {
                  algorithm_ = input.readEnum();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 32
                case 40: {
                  digits_ = input.readEnum();
                  bitField0_ |= 0x00000010;
                  break;
                } // case 40
                case 48: {
                  type_ = input.readEnum();
                  bitField0_ |= 0x00000020;
                  break;
                } // case 48
                case 56: {
                  counter_ = input.readInt64();
                  bitField0_ |= 0x00000040;
                  break;
                } // case 56
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString secret_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes secret = 1;</code>
         * @return The secret.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getSecret() {
          return secret_;
        }
        /**
         * <code>bytes secret = 1;</code>
         * @param value The secret to set.
         * @return This builder for chaining.
         */
        public Builder setSecret(com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          secret_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>bytes secret = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearSecret() {
          bitField0_ = (bitField0_ & ~0x00000001);
          secret_ = getDefaultInstance().getSecret();
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 2;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          name_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          name_ = getDefaultInstance().getName();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          name_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private java.lang.Object issuer_ = "";
        /**
         * <code>string issuer = 3;</code>
         * @return The issuer.
         */
        public java.lang.String getIssuer() {
          java.lang.Object ref = issuer_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            issuer_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string issuer = 3;</code>
         * @return The bytes for issuer.
         */
        public com.google.protobuf.ByteString
            getIssuerBytes() {
          java.lang.Object ref = issuer_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            issuer_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string issuer = 3;</code>
         * @param value The issuer to set.
         * @return This builder for chaining.
         */
        public Builder setIssuer(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          issuer_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>string issuer = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearIssuer() {
          issuer_ = getDefaultInstance().getIssuer();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>string issuer = 3;</code>
         * @param value The bytes for issuer to set.
         * @return This builder for chaining.
         */
        public Builder setIssuerBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          issuer_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }

        private int algorithm_ = 0;
        /**
         * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
         * @return The enum numeric value on the wire for algorithm.
         */
        @java.lang.Override public int getAlgorithmValue() {
          return algorithm_;
        }
        /**
         * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
         * @param value The enum numeric value on the wire for algorithm to set.
         * @return This builder for chaining.
         */
        public Builder setAlgorithmValue(int value) {
          algorithm_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
         * @return The algorithm.
         */
        @java.lang.Override
        public Authenticator.MigrationPayload.Algorithm getAlgorithm() {
          Authenticator.MigrationPayload.Algorithm result = Authenticator.MigrationPayload.Algorithm.forNumber(algorithm_);
          return result == null ? Authenticator.MigrationPayload.Algorithm.UNRECOGNIZED : result;
        }
        /**
         * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
         * @param value The algorithm to set.
         * @return This builder for chaining.
         */
        public Builder setAlgorithm(Authenticator.MigrationPayload.Algorithm value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          algorithm_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.MigrationPayload.Algorithm algorithm = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearAlgorithm() {
          bitField0_ = (bitField0_ & ~0x00000008);
          algorithm_ = 0;
          onChanged();
          return this;
        }

        private int digits_ = 0;
        /**
         * <code>.MigrationPayload.DigitCount digits = 5;</code>
         * @return The enum numeric value on the wire for digits.
         */
        @java.lang.Override public int getDigitsValue() {
          return digits_;
        }
        /**
         * <code>.MigrationPayload.DigitCount digits = 5;</code>
         * @param value The enum numeric value on the wire for digits to set.
         * @return This builder for chaining.
         */
        public Builder setDigitsValue(int value) {
          digits_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }
        /**
         * <code>.MigrationPayload.DigitCount digits = 5;</code>
         * @return The digits.
         */
        @java.lang.Override
        public Authenticator.MigrationPayload.DigitCount getDigits() {
          Authenticator.MigrationPayload.DigitCount result = Authenticator.MigrationPayload.DigitCount.forNumber(digits_);
          return result == null ? Authenticator.MigrationPayload.DigitCount.UNRECOGNIZED : result;
        }
        /**
         * <code>.MigrationPayload.DigitCount digits = 5;</code>
         * @param value The digits to set.
         * @return This builder for chaining.
         */
        public Builder setDigits(Authenticator.MigrationPayload.DigitCount value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          digits_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.MigrationPayload.DigitCount digits = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearDigits() {
          bitField0_ = (bitField0_ & ~0x00000010);
          digits_ = 0;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.MigrationPayload.OtpType type = 6;</code>
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.MigrationPayload.OtpType type = 6;</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          bitField0_ |= 0x00000020;
          onChanged();
          return this;
        }
        /**
         * <code>.MigrationPayload.OtpType type = 6;</code>
         * @return The type.
         */
        @java.lang.Override
        public Authenticator.MigrationPayload.OtpType getType() {
          Authenticator.MigrationPayload.OtpType result = Authenticator.MigrationPayload.OtpType.forNumber(type_);
          return result == null ? Authenticator.MigrationPayload.OtpType.UNRECOGNIZED : result;
        }
        /**
         * <code>.MigrationPayload.OtpType type = 6;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(Authenticator.MigrationPayload.OtpType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000020;
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.MigrationPayload.OtpType type = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000020);
          type_ = 0;
          onChanged();
          return this;
        }

        private long counter_ ;
        /**
         * <code>int64 counter = 7;</code>
         * @return The counter.
         */
        @java.lang.Override
        public long getCounter() {
          return counter_;
        }
        /**
         * <code>int64 counter = 7;</code>
         * @param value The counter to set.
         * @return This builder for chaining.
         */
        public Builder setCounter(long value) {

          counter_ = value;
          bitField0_ |= 0x00000040;
          onChanged();
          return this;
        }
        /**
         * <code>int64 counter = 7;</code>
         * @return This builder for chaining.
         */
        public Builder clearCounter() {
          bitField0_ = (bitField0_ & ~0x00000040);
          counter_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:MigrationPayload.OtpParameters)
      }

      // @@protoc_insertion_point(class_scope:MigrationPayload.OtpParameters)
      private static final Authenticator.MigrationPayload.OtpParameters DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Authenticator.MigrationPayload.OtpParameters();
      }

      public static Authenticator.MigrationPayload.OtpParameters getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<OtpParameters>
          PARSER = new com.google.protobuf.AbstractParser<OtpParameters>() {
        @java.lang.Override
        public OtpParameters parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<OtpParameters> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<OtpParameters> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public Authenticator.MigrationPayload.OtpParameters getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int OTP_PARAMETERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<Authenticator.MigrationPayload.OtpParameters> otpParameters_;
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Authenticator.MigrationPayload.OtpParameters> getOtpParametersList() {
      return otpParameters_;
    }
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Authenticator.MigrationPayload.OtpParametersOrBuilder> 
        getOtpParametersOrBuilderList() {
      return otpParameters_;
    }
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    @java.lang.Override
    public int getOtpParametersCount() {
      return otpParameters_.size();
    }
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    @java.lang.Override
    public Authenticator.MigrationPayload.OtpParameters getOtpParameters(int index) {
      return otpParameters_.get(index);
    }
    /**
     * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
     */
    @java.lang.Override
    public Authenticator.MigrationPayload.OtpParametersOrBuilder getOtpParametersOrBuilder(
        int index) {
      return otpParameters_.get(index);
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_ = 0;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int BATCH_SIZE_FIELD_NUMBER = 3;
    private int batchSize_ = 0;
    /**
     * <code>int32 batch_size = 3;</code>
     * @return The batchSize.
     */
    @java.lang.Override
    public int getBatchSize() {
      return batchSize_;
    }

    public static final int BATCH_INDEX_FIELD_NUMBER = 4;
    private int batchIndex_ = 0;
    /**
     * <code>int32 batch_index = 4;</code>
     * @return The batchIndex.
     */
    @java.lang.Override
    public int getBatchIndex() {
      return batchIndex_;
    }

    public static final int BATCH_ID_FIELD_NUMBER = 5;
    private int batchId_ = 0;
    /**
     * <code>int32 batch_id = 5;</code>
     * @return The batchId.
     */
    @java.lang.Override
    public int getBatchId() {
      return batchId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < otpParameters_.size(); i++) {
        output.writeMessage(1, otpParameters_.get(i));
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (batchSize_ != 0) {
        output.writeInt32(3, batchSize_);
      }
      if (batchIndex_ != 0) {
        output.writeInt32(4, batchIndex_);
      }
      if (batchId_ != 0) {
        output.writeInt32(5, batchId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < otpParameters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, otpParameters_.get(i));
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (batchSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, batchSize_);
      }
      if (batchIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batchIndex_);
      }
      if (batchId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, batchId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Authenticator.MigrationPayload)) {
        return super.equals(obj);
      }
      Authenticator.MigrationPayload other = (Authenticator.MigrationPayload) obj;

      if (!getOtpParametersList()
          .equals(other.getOtpParametersList())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getBatchSize()
          != other.getBatchSize()) return false;
      if (getBatchIndex()
          != other.getBatchIndex()) return false;
      if (getBatchId()
          != other.getBatchId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOtpParametersCount() > 0) {
        hash = (37 * hash) + OTP_PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getOtpParametersList().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
      hash = (37 * hash) + BATCH_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getBatchIndex();
      hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBatchId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Authenticator.MigrationPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Authenticator.MigrationPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Authenticator.MigrationPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Authenticator.MigrationPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Authenticator.MigrationPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Authenticator.MigrationPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Authenticator.MigrationPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Authenticator.MigrationPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Authenticator.MigrationPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Authenticator.MigrationPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Authenticator.MigrationPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Authenticator.MigrationPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Authenticator.MigrationPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MigrationPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MigrationPayload)
        Authenticator.MigrationPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Authenticator.internal_static_MigrationPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Authenticator.internal_static_MigrationPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Authenticator.MigrationPayload.class, Authenticator.MigrationPayload.Builder.class);
      }

      // Construct using Authenticator.MigrationPayload.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (otpParametersBuilder_ == null) {
          otpParameters_ = java.util.Collections.emptyList();
        } else {
          otpParameters_ = null;
          otpParametersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        batchSize_ = 0;
        batchIndex_ = 0;
        batchId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Authenticator.internal_static_MigrationPayload_descriptor;
      }

      @java.lang.Override
      public Authenticator.MigrationPayload getDefaultInstanceForType() {
        return Authenticator.MigrationPayload.getDefaultInstance();
      }

      @java.lang.Override
      public Authenticator.MigrationPayload build() {
        Authenticator.MigrationPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Authenticator.MigrationPayload buildPartial() {
        Authenticator.MigrationPayload result = new Authenticator.MigrationPayload(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Authenticator.MigrationPayload result) {
        if (otpParametersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            otpParameters_ = java.util.Collections.unmodifiableList(otpParameters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.otpParameters_ = otpParameters_;
        } else {
          result.otpParameters_ = otpParametersBuilder_.build();
        }
      }

      private void buildPartial0(Authenticator.MigrationPayload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.batchSize_ = batchSize_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.batchIndex_ = batchIndex_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.batchId_ = batchId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Authenticator.MigrationPayload) {
          return mergeFrom((Authenticator.MigrationPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Authenticator.MigrationPayload other) {
        if (other == Authenticator.MigrationPayload.getDefaultInstance()) return this;
        if (otpParametersBuilder_ == null) {
          if (!other.otpParameters_.isEmpty()) {
            if (otpParameters_.isEmpty()) {
              otpParameters_ = other.otpParameters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOtpParametersIsMutable();
              otpParameters_.addAll(other.otpParameters_);
            }
            onChanged();
          }
        } else {
          if (!other.otpParameters_.isEmpty()) {
            if (otpParametersBuilder_.isEmpty()) {
              otpParametersBuilder_.dispose();
              otpParametersBuilder_ = null;
              otpParameters_ = other.otpParameters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              otpParametersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOtpParametersFieldBuilder() : null;
            } else {
              otpParametersBuilder_.addAllMessages(other.otpParameters_);
            }
          }
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getBatchSize() != 0) {
          setBatchSize(other.getBatchSize());
        }
        if (other.getBatchIndex() != 0) {
          setBatchIndex(other.getBatchIndex());
        }
        if (other.getBatchId() != 0) {
          setBatchId(other.getBatchId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Authenticator.MigrationPayload.OtpParameters m =
                    input.readMessage(
                        Authenticator.MigrationPayload.OtpParameters.parser(),
                        extensionRegistry);
                if (otpParametersBuilder_ == null) {
                  ensureOtpParametersIsMutable();
                  otpParameters_.add(m);
                } else {
                  otpParametersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 16: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                batchSize_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                batchIndex_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                batchId_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Authenticator.MigrationPayload.OtpParameters> otpParameters_ =
        java.util.Collections.emptyList();
      private void ensureOtpParametersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          otpParameters_ = new java.util.ArrayList<Authenticator.MigrationPayload.OtpParameters>(otpParameters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Authenticator.MigrationPayload.OtpParameters, Authenticator.MigrationPayload.OtpParameters.Builder, Authenticator.MigrationPayload.OtpParametersOrBuilder> otpParametersBuilder_;

      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public java.util.List<Authenticator.MigrationPayload.OtpParameters> getOtpParametersList() {
        if (otpParametersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(otpParameters_);
        } else {
          return otpParametersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public int getOtpParametersCount() {
        if (otpParametersBuilder_ == null) {
          return otpParameters_.size();
        } else {
          return otpParametersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Authenticator.MigrationPayload.OtpParameters getOtpParameters(int index) {
        if (otpParametersBuilder_ == null) {
          return otpParameters_.get(index);
        } else {
          return otpParametersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder setOtpParameters(
          int index, Authenticator.MigrationPayload.OtpParameters value) {
        if (otpParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtpParametersIsMutable();
          otpParameters_.set(index, value);
          onChanged();
        } else {
          otpParametersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder setOtpParameters(
          int index, Authenticator.MigrationPayload.OtpParameters.Builder builderForValue) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.set(index, builderForValue.build());
          onChanged();
        } else {
          otpParametersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(Authenticator.MigrationPayload.OtpParameters value) {
        if (otpParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtpParametersIsMutable();
          otpParameters_.add(value);
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(
          int index, Authenticator.MigrationPayload.OtpParameters value) {
        if (otpParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtpParametersIsMutable();
          otpParameters_.add(index, value);
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(
          Authenticator.MigrationPayload.OtpParameters.Builder builderForValue) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.add(builderForValue.build());
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(
          int index, Authenticator.MigrationPayload.OtpParameters.Builder builderForValue) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.add(index, builderForValue.build());
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder addAllOtpParameters(
          java.lang.Iterable<? extends Authenticator.MigrationPayload.OtpParameters> values) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, otpParameters_);
          onChanged();
        } else {
          otpParametersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder clearOtpParameters() {
        if (otpParametersBuilder_ == null) {
          otpParameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          otpParametersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Builder removeOtpParameters(int index) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.remove(index);
          onChanged();
        } else {
          otpParametersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Authenticator.MigrationPayload.OtpParameters.Builder getOtpParametersBuilder(
          int index) {
        return getOtpParametersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Authenticator.MigrationPayload.OtpParametersOrBuilder getOtpParametersOrBuilder(
          int index) {
        if (otpParametersBuilder_ == null) {
          return otpParameters_.get(index);  } else {
          return otpParametersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public java.util.List<? extends Authenticator.MigrationPayload.OtpParametersOrBuilder> 
           getOtpParametersOrBuilderList() {
        if (otpParametersBuilder_ != null) {
          return otpParametersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(otpParameters_);
        }
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Authenticator.MigrationPayload.OtpParameters.Builder addOtpParametersBuilder() {
        return getOtpParametersFieldBuilder().addBuilder(
            Authenticator.MigrationPayload.OtpParameters.getDefaultInstance());
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public Authenticator.MigrationPayload.OtpParameters.Builder addOtpParametersBuilder(
          int index) {
        return getOtpParametersFieldBuilder().addBuilder(
            index, Authenticator.MigrationPayload.OtpParameters.getDefaultInstance());
      }
      /**
       * <code>repeated .MigrationPayload.OtpParameters otp_parameters = 1;</code>
       */
      public java.util.List<Authenticator.MigrationPayload.OtpParameters.Builder> 
           getOtpParametersBuilderList() {
        return getOtpParametersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Authenticator.MigrationPayload.OtpParameters, Authenticator.MigrationPayload.OtpParameters.Builder, Authenticator.MigrationPayload.OtpParametersOrBuilder> 
          getOtpParametersFieldBuilder() {
        if (otpParametersBuilder_ == null) {
          otpParametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Authenticator.MigrationPayload.OtpParameters, Authenticator.MigrationPayload.OtpParameters.Builder, Authenticator.MigrationPayload.OtpParametersOrBuilder>(
                  otpParameters_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          otpParameters_ = null;
        }
        return otpParametersBuilder_;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {

        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>int32 batch_size = 3;</code>
       * @return The batchSize.
       */
      @java.lang.Override
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>int32 batch_size = 3;</code>
       * @param value The batchSize to set.
       * @return This builder for chaining.
       */
      public Builder setBatchSize(int value) {

        batchSize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batch_size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        batchSize_ = 0;
        onChanged();
        return this;
      }

      private int batchIndex_ ;
      /**
       * <code>int32 batch_index = 4;</code>
       * @return The batchIndex.
       */
      @java.lang.Override
      public int getBatchIndex() {
        return batchIndex_;
      }
      /**
       * <code>int32 batch_index = 4;</code>
       * @param value The batchIndex to set.
       * @return This builder for chaining.
       */
      public Builder setBatchIndex(int value) {

        batchIndex_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batch_index = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchIndex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batchIndex_ = 0;
        onChanged();
        return this;
      }

      private int batchId_ ;
      /**
       * <code>int32 batch_id = 5;</code>
       * @return The batchId.
       */
      @java.lang.Override
      public int getBatchId() {
        return batchId_;
      }
      /**
       * <code>int32 batch_id = 5;</code>
       * @param value The batchId to set.
       * @return This builder for chaining.
       */
      public Builder setBatchId(int value) {

        batchId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 batch_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        batchId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MigrationPayload)
    }

    // @@protoc_insertion_point(class_scope:MigrationPayload)
    private static final Authenticator.MigrationPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Authenticator.MigrationPayload();
    }

    public static Authenticator.MigrationPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MigrationPayload>
        PARSER = new com.google.protobuf.AbstractParser<MigrationPayload>() {
      @java.lang.Override
      public MigrationPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MigrationPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MigrationPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Authenticator.MigrationPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MigrationPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MigrationPayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MigrationPayload_OtpParameters_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MigrationPayload_OtpParameters_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/authenticator.proto\"\214\005\n" +
      "\020MigrationPayload\0227\n\016otp_parameters\030\001 \003(" +
      "\0132\037.MigrationPayload.OtpParameters\022\017\n\007ve" +
      "rsion\030\002 \001(\005\022\022\n\nbatch_size\030\003 \001(\005\022\023\n\013batch" +
      "_index\030\004 \001(\005\022\020\n\010batch_id\030\005 \001(\005\032\325\001\n\rOtpPa" +
      "rameters\022\016\n\006secret\030\001 \001(\014\022\014\n\004name\030\002 \001(\t\022\016" +
      "\n\006issuer\030\003 \001(\t\022.\n\talgorithm\030\004 \001(\0162\033.Migr" +
      "ationPayload.Algorithm\022,\n\006digits\030\005 \001(\0162\034" +
      ".MigrationPayload.DigitCount\022\'\n\004type\030\006 \001" +
      "(\0162\031.MigrationPayload.OtpType\022\017\n\007counter" +
      "\030\007 \001(\003\"y\n\tAlgorithm\022\031\n\025ALGORITHM_UNSPECI" +
      "FIED\020\000\022\022\n\016ALGORITHM_SHA1\020\001\022\024\n\020ALGORITHM_" +
      "SHA256\020\002\022\024\n\020ALGORITHM_SHA512\020\003\022\021\n\rALGORI" +
      "THM_MD5\020\004\"U\n\nDigitCount\022\033\n\027DIGIT_COUNT_U" +
      "NSPECIFIED\020\000\022\023\n\017DIGIT_COUNT_SIX\020\001\022\025\n\021DIG" +
      "IT_COUNT_EIGHT\020\002\"I\n\007OtpType\022\030\n\024OTP_TYPE_" +
      "UNSPECIFIED\020\000\022\021\n\rOTP_TYPE_HOTP\020\001\022\021\n\rOTP_" +
      "TYPE_TOTP\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MigrationPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MigrationPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MigrationPayload_descriptor,
        new java.lang.String[] { "OtpParameters", "Version", "BatchSize", "BatchIndex", "BatchId", });
    internal_static_MigrationPayload_OtpParameters_descriptor =
      internal_static_MigrationPayload_descriptor.getNestedTypes().get(0);
    internal_static_MigrationPayload_OtpParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MigrationPayload_OtpParameters_descriptor,
        new java.lang.String[] { "Secret", "Name", "Issuer", "Algorithm", "Digits", "Type", "Counter", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
